name: Code Quality

on:
  push:
    branches: [main, release/*]
  pull_request:
    branches: [main, release/*]

# Cancel previous runs if new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        tox_env: ["pre-commit-all", "build-docs"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install tox
      - name: Run code quality checks
        run: echo "Running tox ${{ matrix.tox_env }}"
