name: Unit tests

on:
  pull_request:
    branches: [main, release/*]
    paths:
      - ".github/workflows/unit_tests.yml"
      - "my_proj/**"
      - "pyproject.toml"
  push:
    branches: [main, release/*]

# Cancel previous runs if new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # Install cmake to build onnxsim from sdists for Python 3.12 until http://github.com/daquexian/onnx-simplifier/pull/353
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y cmake
          pip install onnxsim
          pip install tox
          pip install -e .
          python -c "import my_proj.quantization as q; print(q)"
      - name: Run unit tests
        run: echo "Running tox -e py312-torch27-unit"
